Develop drv_db and define header imports order
WattRex/Battery-Cyclers-Controler pull request #4
Opened 2023-07-13 08:07 UTC by javibu13

2023-07-13 09:17 UTC, mariuscrsn requested changes

2023-07-13 09:17 UTC, mariuscrsn commented on code/drv/drv_db/drv_db_types.py
> +    INTER_ERROR = 'INTER'
Change to INTERNAL_ERROR. Use same values as names.

2023-07-13 09:17 UTC, mariuscrsn commented on code/drv/drv_db/drv_db_dao.py
Remove number from integer type. Add unsigned if necessary. https://stackoverflow.com/questions/19717738/how-to-define-an-unsigned-integer-in-sqlalchemy

2023-07-13 09:28 UTC, javibu13 commented on code/drv/drv_db/drv_db_dao.py
Done.

2023-07-13 09:53 UTC, mariuscrsn approved these changes

2023-07-17 12:42 UTC, mariuscrsn approved these changes

2023-07-17 12:42 UTC, merged