small changes in imports and ajust to pep8
WattRex/Battery-Cyclers-Controler pull request #6
Opened 2023-07-13 12:46 UTC by luroche

approve me now!!

2023-07-13 13:41 UTC, mariuscrsn requested changes

2023-07-14 06:20 UTC, luroche commented on code/drv/drv_scpi/drv_scpi.py
> +        msg = self.__serial.readall()
For example, in the multimeter, if the complet message is: 'FETCH?'\n'1.19939508e1', using read_until(b'\n') only read FETCH?.

2023-07-17 12:39 UTC, mariuscrsn commented on code/drv/drv_scpi/drv_scpi.py
> +        msg = self.__serial.readall()
It must be handler in the upper module (`drv_bk`).

2023-07-17 13:52 UTC, RobertoAldea requested changes

2023-07-17 13:52 UTC, RobertoAldea commented on code/drv/drv_scpi/example.py
> +# log = sys_log_logger_get_module_logger(__name__)
When uploading try to uncomment neccesary code in future

2023-07-17 13:52 UTC, RobertoAldea commented on code/drv/drv_scpi/example.py
>      print(source.read_device_info())
Try to use logger instead of prints

2023-07-20 07:32 UTC, RobertoAldea requested changes

2023-07-20 07:46 UTC, luroche commented on code/drv/drv_scpi/example.py
> +# log = sys_log_logger_get_module_logger(__name__)
Done.

2023-07-20 07:48 UTC, luroche commented on code/drv/drv_scpi/example.py
>      print(source.read_device_info())
Done.

2023-07-20 07:49 UTC, luroche commented on code/drv/drv_scpi/drv_scpi.py
>  class _DefaultSerialParamsC:
@mariuscrsn

2023-08-16 12:39 UTC, closed without merging